version: '3'

services:
  mongo:
    image: mongo
    restart: always
    container_name: "mongodb"
    working_dir: "/mongodbdata/"
    ports:
      - '27017:27017'
    volumes:
      - "/mongodbdata/:/data/db"