version: '3'

services:
  front-end:
    restart: "unless-stopped"
    container_name: "fronty"
    user: "${UID}:${GID}"
    build:
      context: 'frontend/'
      dockerfile: 'docker/Dockerfile'
    command: 'python src/1D_Dash.py'
    environment:
      DATA_DIR: "${COMPOSE_PROJECT_NAME}_data-m"
    volumes:
      - ./data:/app/work/data
      - ./frontend/src:/app/work/src
      - ./frontend/tmp:/app/tmp
    ports:
      - '8050:8050'

  automatic-tags:
    container_name: "autotag"
    user: "${UID}:${GID}"
    build:
      context: 'automatic_detection/'
      dockerfile: 'docker/Dockerfile'
    command: 'python block_detection.py data data/results'
    depends_on: 
      - "splash-ml"
    volumes:
      - ./automatic_detection:/app/work
      - ./data:/app/work/data
      
  mongo_mlex:
    image: mongo
    restart: always
    container_name: "mongodb_mlex"
    working_dir: "/mongodbdata/"
#    ports:
#      - '27017:27017'
    volumes:
      - "/mongodbdata/:/data/db"

  splash-ml:
    restart: "unless-stopped"
    container_name: "splash"
    user: "${UID}:${GID}"
    build:
      context: 'splash-ml/'
      dockerfile: 'Dockerfile'
    depends_on:
      - "mongo_mlex"
    volumes:
      - ../splash-ml:/app/work
    ports:
      - '8000:8000'
    environment:
       MONGO_DB_URI: mongodb://mongodb:27017/tagging

volumes: # create named dir and link it to the data folder, so all services can 
         # use
  data-m:
    driver: local
    driver_opts:
      type: "none"
      device: "./frontend/data/"
      o: "bind"